## np.where()函数测试

In [1]:
import numpy as np

print("=" * 60)
print("测试 1：单参数 np.where —— 返回索引")
print("=" * 60)

a = np.array([1, -2, 3, -4, 5, -6])
idx = np.where(a > 0)
print(f"数组: {a}")
print(f"np.where(a > 0) = {idx}")
print(f"类型: {type(idx)}, 元素类型: {type(idx[0])}")
print(f"取出的值: {a[idx]}")
print()

print("=" * 60)
print("测试 2：单参数返回的是元组（重要！）")
print("=" * 60)

print(f"idx 是元组吗? {isinstance(idx, tuple)}")
print(f"idx 长度: {len(idx)}")
print(f"idx[0] = {idx[0]}")
print()

print("=" * 60)
print("测试 3：三参数 np.where —— 条件选择")
print("=" * 60)

a = np.array([1, -2, 3, -4, 5, -6])
result = np.where(a > 0, a, 0)
print(f"数组: {a}")
print(f"np.where(a > 0, a, 0) = {result}  # 负数变 0")

result2 = np.where(a > 0, "正", "负")
print(f"np.where(a > 0, '正', '负') = {result2}")
print()

print("=" * 60)
print("测试 4：二维数组的索引")
print("=" * 60)

M = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
rows, cols = np.where(M > 5)
print(f"矩阵:\n{M}")
print(f"np.where(M > 5) = {np.where(M > 5)}")
print(f"rows = {rows}")
print(f"cols = {cols}")
print(f"对应元素: {M[rows, cols]}")
print()

print("=" * 60)
print("测试 5：三维数组的索引")
print("=" * 60)

V = np.arange(24).reshape(2, 3, 4)
idx3 = np.where(V > 20)
print(f"三维数组 shape: {V.shape}")
print(f"np.where(V > 20) 返回 {len(idx3)} 个索引数组")
print(f"索引 0: {idx3[0]}")
print(f"索引 1: {idx3[1]}")
print(f"索引 2: {idx3[2]}")
print(f"对应值: {V[idx3]}")
print()

print("=" * 60)
print("测试 6：模拟你代码里的 small_angles 场景")
print("=" * 60)

# 模拟：布尔掩码 * 非零掩码
angles = np.array([0.9, 0.95, 1.0, 0.98, 0.5, 0.99])
nonzero = np.array([1, 1, 0, 1, 1, 1], dtype=bool)  # 第 3 个是"零向量"

mask = (angles > 0.95) * nonzero
print(f"angles  = {angles}")
print(f"nonzero = {nonzero}")
print(f"mask    = {mask}")

idx = np.where(mask)
print(f"np.where(mask) = {idx}")
print(f"索引数组类型: {type(idx[0])}")
print(f"满足条件的索引: {idx[0]}")
print(f"对应 angles: {angles[idx[0]]}")
print()

print("=" * 60)
print("测试 7：空结果的返回")
print("=" * 60)

a = np.array([1, 2, 3])
idx = np.where(a > 100)
print(f"np.where(a > 100) = {idx}")
print(f"idx[0] = {idx[0]}, 形状: {idx[0].shape}")
print()

print("=" * 60)
print("测试 8：广播（三参数）")
print("=" * 60)

a = np.array([[1, 2, 3],
              [4, 5, 6]])
cond = a > 3
x = np.array([100, 200, 300])   # 广播到每一行
y = np.array([0, 0, 0])
result = np.where(cond, x, y)
print(f"cond:\n{cond}")
print(f"np.where(cond, x, y):\n{result}")
print()

print("=" * 60)
print("测试 9：边界情况 —— 全部 True / 全部 False")
print("=" * 60)

a = np.array([1, 2, 3])
print(f"全 True : {np.where(a > 0)[0]}")
print(f"全 False: {np.where(a < 0)[0]}")
print()

print("=" * 60)
print("测试 10：np.where 常用于筛选（等价写法对比）")
print("=" * 60)

a = np.array([1, -2, 3, -4, 5])

# 写法 1：布尔索引
r1 = a[a > 0]

# 写法 2：np.where 单参数
r2 = a[np.where(a > 0)]

# 写法 3：np.where 三参数（过滤成 0）
r3 = np.where(a > 0, a, 0)

print(f"布尔索引        : {r1}")
print(f"np.where 单参数 : {r2}")
print(f"np.where 三参数 : {r3}   # 注意：保留了长度，负数变 0")

测试 1：单参数 np.where —— 返回索引
数组: [ 1 -2  3 -4  5 -6]
np.where(a > 0) = (array([0, 2, 4]),)
类型: <class 'tuple'>, 元素类型: <class 'numpy.ndarray'>
取出的值: [1 3 5]

测试 2：单参数返回的是元组（重要！）
idx 是元组吗? True
idx 长度: 1
idx[0] = [0 2 4]

测试 3：三参数 np.where —— 条件选择
数组: [ 1 -2  3 -4  5 -6]
np.where(a > 0, a, 0) = [1 0 3 0 5 0]  # 负数变 0
np.where(a > 0, '正', '负') = ['正' '负' '正' '负' '正' '负']

测试 4：二维数组的索引
矩阵:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
np.where(M > 5) = (array([1, 2, 2, 2]), array([2, 0, 1, 2]))
rows = [1 2 2 2]
cols = [2 0 1 2]
对应元素: [6 7 8 9]

测试 5：三维数组的索引
三维数组 shape: (2, 3, 4)
np.where(V > 20) 返回 3 个索引数组
索引 0: [1 1 1]
索引 1: [2 2 2]
索引 2: [1 2 3]
对应值: [21 22 23]

测试 6：模拟你代码里的 small_angles 场景
angles  = [0.9  0.95 1.   0.98 0.5  0.99]
nonzero = [ True  True False  True  True  True]
mask    = [False False False  True False  True]
np.where(mask) = (array([3, 5]),)
索引数组类型: <class 'numpy.ndarray'>
满足条件的索引: [3 5]
对应 angles: [0.98 0.99]

测试 7：空结果的返回
np.where(a > 100) = (array([], dtype=int64),)
idx[0] = [], 形状: (0,)


In [11]:
c=np.array([[1, 1, 0],[0,0,1]], dtype=bool) 
b=np.array([[1, 0, 0],[0,1,1]], dtype=bool)
print(b*c) 
place=np.where(b*c)  # 返回满足条件的索引
print(place)
a=np.array([[1, 2, 3], [4, 5, 6]])
print(a[place])  # 使用索引提取对应的元素
d=np.linalg.norm(a[place], axis=0)
print(d)


[[ True False False]
 [False False  True]]
(array([0, 1]), array([0, 2]))
[1 6]
6.082762530298219
